---
- name: Converge
  hosts: all
  become: true

  vars:
    # Allow swap in test environments (hard to control in some Docker envs).
    kubernetes_kubelet_extra_args: "--fail-swap-on=false --cgroup-driver=cgroupfs"
    docker_install_compose: false

  pre_tasks:
    - name: Ensure test dependencies are installed (RedHat).
      package: name=iproute state=present

    - name: Gather facts.
      action: setup

  roles:
    - role: geerlingguy.docker
    - role: geerlingguy.kubernetes

  post_tasks:
    - name: Get cluster info.
      command: kubectl cluster-info
      changed_when: false
      register: kubernetes_info

    - name: Print cluster info.
      debug: var=kubernetes_info.stdout

    - name: Get all running pods.
      command: kubectl get pods --all-namespaces
      changed_when: false
      register: kubernetes_pods

    - name: Print list of running pods.
      debug: var=kubernetes_pods.stdout
