---
- hosts: k8s_cluster
  gather_facts: yes
  become: yes

  vars:
    # Role docker
    docker_install_compose: false
    docker_users:
      - "{{ ansible_user }}"
    # Role kubernetes
    # You can set proxy variables if needed here:
    #proxy_config:
    #  http_proxy: "http://my_proxy:port"
    #  https_proxy: "http://my_proxy:port"
    #  HTTP_PROXY: "my_proxy:port"
    #  HTTPS_PROXY: "my_proxy:port"
    #  NO_PROXY: "localhost,127.0.*"

  environment: "{{ proxy_config }}"
 
  roles:
    - docker
    - kubernetes

  tasks: []
