---
- hosts: ctrl
  gather_facts: no

  vars:
    proxy_config:
      http_proxy: "{{ lookup('file','/tmp/my_http_proxy', errors='ignore') | default('') }}"
      https_proxy: "{{ lookup('file','/tmp/my_https_proxy', errors='ignore') | default('') }}"
      HTTP_PROXY: "{{ lookup('file','/tmp/my_HTTP_PROXY', errors='ignore')| default('') }}"
      HTTPS_PROXY: "{{ lookup('file','/tmp/my_HTTPS_PROXY', errors='ignore') | default('') }}"

  tasks:
  - name: Copy vagrant insecure key
    copy:
      src: /vagrant/vagrant_insecure_private_key
      dest: ~/.ssh/insecure_private_key
      mode: '0600'

- import_playbook: main.yml
